### PR TITLE
EIP-2771 support for Mysterium's meta transactions

### PR DESCRIPTION
**Pull request by chompomonim**
When in 2019 we were working on payment system there was no known solutions for “meta transactions”. Now, in 2022, there are a few widely used meta transaction solutions. Crypto community (building on top of EVM compatible chains) has reached some consensus on minimal interoperability solution for meta transactions support on smart contracts level. 

This proposal describes how we could implement support for __EIP2771__ with minimal changes of our smart contracts, services and node itself.

### CODE REVIEW

**Comment by Snawoot** [comment]
Thanks!

Can you please outline sequence of implied changes and how can we maintain backwards compatibility on each step?

**Comment by Snawoot** [comment]
i.e. which set of changes goes first and how do we handle older nodes on each step

**Comment by Guillembonet** [comment]
As far as I understand this details changes with hermes smart contract only right? We would then still use the same non-EIP2771 logic with registrations (so, no code changes in registry) no?

**Comment by chompomonim** [comment]
> i.e. which set of changes goes first and how do we handle older nodes on each step

Added `Proposed implementation Roadmap` section into end of document.

By the way, keep in mind, that to upgrade `Forwarder` we don't need to register new Hermes, we can simply add one more forwarder into already registered hermesses.

**Comment by chompomonim** [comment]
> As far as I understand this details changes with hermes smart contract only right? We would then still use the same non-EIP2771 logic with registrations (so, no code changes in registry) no?

The same explained logic could be extended into any our smart contract and any call in that smart contract. Hermes and promise settlement were chosen as most often used transactions to visualised general idea.

**Review by tomasmik — APPROVED** [review]
Seems like plenty of information is given in order to implement this. Though this again looks like another hermes migration etc. which is a pain.

**Pull request merged**
